package com.crimsonedge.studioadmin.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

enum class ThemeMode { SYSTEM, LIGHT, DARK }

enum class AppTheme(
    val displayName: String,
    val gradientStart: Color,
    val gradientEnd: Color,
    val lightScheme: androidx.compose.material3.ColorScheme,
    val darkScheme: androidx.compose.material3.ColorScheme
) {
    ROSE(
        displayName = "Rose",
        gradientStart = Color(0xFFDB2777),
        gradientEnd = Color(0xFFA855F7),
        lightScheme = lightColorScheme(
            primary = Color(0xFFDB2777),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFFCE7F3),
            onPrimaryContainer = Color(0xFF4A0D2A),
            secondary = Color(0xFF9333EA),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFF3E8FF),
            onSecondaryContainer = Color(0xFF2E1065),
            background = Color(0xFFFFFBFE),
            onBackground = Color(0xFF1C1B1F),
            surface = Color.White,
            onSurface = Color(0xFF1C1B1F),
            surfaceVariant = Color(0xFFF5F5F5),
            onSurfaceVariant = Color(0xFF49454E),
            outline = Color(0xFFE0E0E0),
            error = Color(0xFFEF4444),
            onError = Color.White
        ),
        darkScheme = darkColorScheme(
            primary = Color(0xFFEC4899),
            onPrimary = Color(0xFF4A0D2A),
            primaryContainer = Color(0xFF6B1A3A),
            onPrimaryContainer = Color(0xFFF472B6),
            secondary = Color(0xFFA855F7),
            onSecondary = Color(0xFF2E1065),
            secondaryContainer = Color(0xFF3B1F6E),
            onSecondaryContainer = Color(0xFFC084FC),
            background = Color(0xFF0F0F0F),
            onBackground = Color(0xFFE6E1E5),
            surface = Color(0xFF1A1A1A),
            onSurface = Color(0xFFE6E1E5),
            surfaceVariant = Color(0xFF262626),
            onSurfaceVariant = Color(0xFFCAC4D0),
            outline = Color(0xFF3A3A3A),
            error = Color(0xFFF87171),
            onError = Color.Black
        )
    ),

    OCEAN(
        displayName = "Ocean",
        gradientStart = Color(0xFF2563EB),
        gradientEnd = Color(0xFF06B6D4),
        lightScheme = lightColorScheme(
            primary = Color(0xFF2563EB),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFDBEAFE),
            onPrimaryContainer = Color(0xFF1E3A5F),
            secondary = Color(0xFF06B6D4),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFCFFAFE),
            onSecondaryContainer = Color(0xFF164E63),
            background = Color(0xFFFAFCFF),
            onBackground = Color(0xFF1C1B1F),
            surface = Color.White,
            onSurface = Color(0xFF1C1B1F),
            surfaceVariant = Color(0xFFF0F5FA),
            onSurfaceVariant = Color(0xFF44474E),
            outline = Color(0xFFDDE3EA),
            error = Color(0xFFEF4444),
            onError = Color.White
        ),
        darkScheme = darkColorScheme(
            primary = Color(0xFF60A5FA),
            onPrimary = Color(0xFF1E3A5F),
            primaryContainer = Color(0xFF1E40AF),
            onPrimaryContainer = Color(0xFF93C5FD),
            secondary = Color(0xFF22D3EE),
            onSecondary = Color(0xFF164E63),
            secondaryContainer = Color(0xFF0E7490),
            onSecondaryContainer = Color(0xFF67E8F9),
            background = Color(0xFF0C0F14),
            onBackground = Color(0xFFE1E3E6),
            surface = Color(0xFF161A22),
            onSurface = Color(0xFFE1E3E6),
            surfaceVariant = Color(0xFF222830),
            onSurfaceVariant = Color(0xFFC4CAD4),
            outline = Color(0xFF353B44),
            error = Color(0xFFF87171),
            onError = Color.Black
        )
    ),

    SUNSET(
        displayName = "Sunset",
        gradientStart = Color(0xFFEA580C),
        gradientEnd = Color(0xFFF59E0B),
        lightScheme = lightColorScheme(
            primary = Color(0xFFEA580C),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFFFEDD5),
            onPrimaryContainer = Color(0xFF5C2D0E),
            secondary = Color(0xFFF59E0B),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFFEF3C7),
            onSecondaryContainer = Color(0xFF713F12),
            background = Color(0xFFFFFCFA),
            onBackground = Color(0xFF1C1B1F),
            surface = Color.White,
            onSurface = Color(0xFF1C1B1F),
            surfaceVariant = Color(0xFFFAF5F0),
            onSurfaceVariant = Color(0xFF4E4744),
            outline = Color(0xFFE8DDD5),
            error = Color(0xFFEF4444),
            onError = Color.White
        ),
        darkScheme = darkColorScheme(
            primary = Color(0xFFFB923C),
            onPrimary = Color(0xFF5C2D0E),
            primaryContainer = Color(0xFF9A3412),
            onPrimaryContainer = Color(0xFFFDBA74),
            secondary = Color(0xFFFBBF24),
            onSecondary = Color(0xFF713F12),
            secondaryContainer = Color(0xFF92400E),
            onSecondaryContainer = Color(0xFFFDE68A),
            background = Color(0xFF100D0A),
            onBackground = Color(0xFFE6E1DB),
            surface = Color(0xFF1C1814),
            onSurface = Color(0xFFE6E1DB),
            surfaceVariant = Color(0xFF2A2520),
            onSurfaceVariant = Color(0xFFD0C8C0),
            outline = Color(0xFF3E3830),
            error = Color(0xFFF87171),
            onError = Color.Black
        )
    ),

    EMERALD(
        displayName = "Emerald",
        gradientStart = Color(0xFF059669),
        gradientEnd = Color(0xFF0D9488),
        lightScheme = lightColorScheme(
            primary = Color(0xFF059669),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFD1FAE5),
            onPrimaryContainer = Color(0xFF064E3B),
            secondary = Color(0xFF0D9488),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFCCFBF1),
            onSecondaryContainer = Color(0xFF134E4A),
            background = Color(0xFFFAFFFD),
            onBackground = Color(0xFF1C1B1F),
            surface = Color.White,
            onSurface = Color(0xFF1C1B1F),
            surfaceVariant = Color(0xFFF0FAF5),
            onSurfaceVariant = Color(0xFF44504A),
            outline = Color(0xFFDDE8E2),
            error = Color(0xFFEF4444),
            onError = Color.White
        ),
        darkScheme = darkColorScheme(
            primary = Color(0xFF34D399),
            onPrimary = Color(0xFF064E3B),
            primaryContainer = Color(0xFF065F46),
            onPrimaryContainer = Color(0xFF6EE7B7),
            secondary = Color(0xFF2DD4BF),
            onSecondary = Color(0xFF134E4A),
            secondaryContainer = Color(0xFF115E59),
            onSecondaryContainer = Color(0xFF5EEAD4),
            background = Color(0xFF0A100D),
            onBackground = Color(0xFFDDE6E1),
            surface = Color(0xFF141C18),
            onSurface = Color(0xFFDDE6E1),
            surfaceVariant = Color(0xFF202A24),
            onSurfaceVariant = Color(0xFFC0D0C8),
            outline = Color(0xFF333E38),
            error = Color(0xFFF87171),
            onError = Color.Black
        )
    ),

    LAVENDER(
        displayName = "Lavender",
        gradientStart = Color(0xFF7C3AED),
        gradientEnd = Color(0xFF4F46E5),
        lightScheme = lightColorScheme(
            primary = Color(0xFF7C3AED),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFEDE9FE),
            onPrimaryContainer = Color(0xFF3B1A8B),
            secondary = Color(0xFF4F46E5),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFE0E7FF),
            onSecondaryContainer = Color(0xFF312E81),
            background = Color(0xFFFCFBFF),
            onBackground = Color(0xFF1C1B1F),
            surface = Color.White,
            onSurface = Color(0xFF1C1B1F),
            surfaceVariant = Color(0xFFF3F0FA),
            onSurfaceVariant = Color(0xFF48454E),
            outline = Color(0xFFE0DDE8),
            error = Color(0xFFEF4444),
            onError = Color.White
        ),
        darkScheme = darkColorScheme(
            primary = Color(0xFFA78BFA),
            onPrimary = Color(0xFF3B1A8B),
            primaryContainer = Color(0xFF5B21B6),
            onPrimaryContainer = Color(0xFFC4B5FD),
            secondary = Color(0xFF818CF8),
            onSecondary = Color(0xFF312E81),
            secondaryContainer = Color(0xFF3730A3),
            onSecondaryContainer = Color(0xFFA5B4FC),
            background = Color(0xFF0D0B14),
            onBackground = Color(0xFFE3E1E8),
            surface = Color(0xFF18161F),
            onSurface = Color(0xFFE3E1E8),
            surfaceVariant = Color(0xFF24222C),
            onSurfaceVariant = Color(0xFFCBC7D4),
            outline = Color(0xFF38353F),
            error = Color(0xFFF87171),
            onError = Color.Black
        )
    ),

    SLATE(
        displayName = "Slate",
        gradientStart = Color(0xFF475569),
        gradientEnd = Color(0xFF64748B),
        lightScheme = lightColorScheme(
            primary = Color(0xFF475569),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFE2E8F0),
            onPrimaryContainer = Color(0xFF1E293B),
            secondary = Color(0xFF64748B),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFF1F5F9),
            onSecondaryContainer = Color(0xFF334155),
            background = Color(0xFFFAFAFC),
            onBackground = Color(0xFF1C1B1F),
            surface = Color.White,
            onSurface = Color(0xFF1C1B1F),
            surfaceVariant = Color(0xFFF1F3F5),
            onSurfaceVariant = Color(0xFF474B52),
            outline = Color(0xFFDFE2E6),
            error = Color(0xFFEF4444),
            onError = Color.White
        ),
        darkScheme = darkColorScheme(
            primary = Color(0xFF94A3B8),
            onPrimary = Color(0xFF1E293B),
            primaryContainer = Color(0xFF334155),
            onPrimaryContainer = Color(0xFFCBD5E1),
            secondary = Color(0xFF94A3B8),
            onSecondary = Color(0xFF334155),
            secondaryContainer = Color(0xFF475569),
            onSecondaryContainer = Color(0xFFCBD5E1),
            background = Color(0xFF0B0D10),
            onBackground = Color(0xFFE0E2E6),
            surface = Color(0xFF151820),
            onSurface = Color(0xFFE0E2E6),
            surfaceVariant = Color(0xFF21252E),
            onSurfaceVariant = Color(0xFFC4C8D0),
            outline = Color(0xFF343840),
            error = Color(0xFFF87171),
            onError = Color.Black
        )
    )
}
